on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.ROLE_ARN}}
          aws-region: us-east-1
      - name: Create deployment package
        run: zip -r function.zip . -x .github
      - name: Deploy to Lambda
        run: aws lambda update-function-code --function-name ${{vars.FUNCTION_NAME}} --zip-file fileb://function.zip
